name: Production Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prd
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check out
        uses: actions/checkout@v2
      - name: Install package
        run: |
          sudo apt update
          yarn
      - name: Test
        run: yarn test taberogu
      - name: Deploy
        run: yarn deploy-prd
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          HOOK_TARGET_BRANCH: main
          KALDI_CHANNEL_ACCESS_TOKEN: ${{ secrets.KALDI_CHANNEL_ACCESS_TOKEN }}
          KALDI_TARGET_PREFECTURE: ${{ secrets.KALDI_TARGET_PREFECTURE }}
          SHAMAISON_CHANNEL_ACCESS_TOKEN: ${{ secrets.SHAMAISON_CHANNEL_ACCESS_TOKEN }}
          SHAMAISON_TARGET_STATIONS: ${{ secrets.SHAMAISON_TARGET_STATIONS }}
          SHAMAISON_TARGET_FLOOR_PLANS: ${{ secrets.SHAMAISON_TARGET_FLOOR_PLANS }}
